id: P009121
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC54
  title: སྐྱེས་བུ་གསུམ་གྱི་ལམ་གྱི་རིམ་པ་རྒྱས་པ་འཁྲིད་དུ་སྦྱར་བ་བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མ།
  author: ''
  volumes:
    2eb703da770249cdaeb4136d0d554467:
      image_group_id: I2PD17600
      title: ''
      volume_number: 1
      total_pages: 620
