id: I224422B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:03:29+00:00'
last_modified: '2022-06-08T08:46:26.055552+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC54
  title: སྐྱེས་བུ་གསུམ་གྱི་ལམ་གྱི་རིམ་པ་རྒྱས་པ་འཁྲིད་དུ་སྦྱར་བ་བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    40AA:
      image_group_id: I2PD17600
      title: ''
      total_pages: 620
      order: 1
      base_file: 40AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
