id: I224422B0
legacy_id: P009121
ocr_import_info:
  bdrc_scan_id: W1AC54
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T06:59:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:36:34.273377+00:00'
last_modified: 2022-08-31 02:37:36.521147
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC54
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC54
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐྱེས་བུ་གསུམ་གྱི་ལམ་གྱི་རིམ་པ་རྒྱས་པ་འཁྲིད་དུ་སྦྱར་བ་བྱང་ཆུབ་ལམ་གྱི་སྒྲོན་མ།
  author: བོ་དོང་པཎ་ཆེན་ཕྱོགས་ལས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.8237554247946509
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD17600:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD17600
      total_pages: 620
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD17600.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8237554247946509
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
